# -*- coding: utf-8 -*-


"""
/***************************************************************************
 SyncLayout
                                 A QGIS plugin
 マップとレイアウトビューの位置を同期します。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-25
        copyright            : (C) 2021 by h.s
        email                : metsagen@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SyncLayout class from file SyncLayout.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Sync_Layout import SyncLayout
    return SyncLayout(iface)
