# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SyncLayoutDialog
                                 A QGIS plugin
 マップとレイアウトビューの位置を同期します。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-25
        git sha              : $Format:%H$
        copyright            : (C) 2021 by h.s
        email                : metsagen@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

##import os
##
##from qgis.PyQt import uic
##from qgis.PyQt.uic import loadUi
##from qgis.PyQt import QtWidgets
##
### This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
###FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'Sync_Layout_dialog_base.ui'))
##
##pluginPath = os.path.dirname(__file__)
##uiPath = os.path.join(pluginPath, 'Sync_Layout_dialog_base.ui')
##WIDGET, BASE = uic.loadUiType(uiPath)
##
##class SyncLayoutDialog(BASE, WIDGET):
##    def __init__(self, parent=None):
##        """Constructor."""
##        super(SyncLayoutDialog, self).__init__(parent)
##        # Set up the user interface from Designer through FORM_CLASS.
##        # After self.setupUi() you can access any designer object by doing
##        # self.<objectname>, and you can use autoconnect slots - see
##        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
##        # #widgets-and-dialogs-with-auto-connect
##
##        #self.setupUi(self)
##        self.dlg=loadUi(uiPath, self)

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Sync_Layout_dialog_base.ui'))


class SyncLayoutDialog(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(SyncLayoutDialog, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()


